# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mstrdm
tagline:          'Memorable Fancies'
description:      'This is, or will be, my webpage.'
url:              http://www.masteradamo.uk
baseurl:          /

author:
  name:           'Stephen McGregor'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Google services
google_analytics: UA-97408615-1

